### ISSUE TITLE
Add a LIBDIR variable in the cmakefile to allow install in /usr/lib64

### ISSUE THREAD

**Issue by ycollet** [ssj71/infamousPlugins#2]
Fedora distro install lv2 plugins into /usr/lib64/lv2.
Add a LIBDIR variable in the cmakefile to allow install in /usr/lib64.

**Comment by ssj71** [comment]
sorry, I'm trying to add this but can't figure out how. 
I've tried changing it so that I create a cmake variable LV2_INSTALL_DIR=lib/lv2/ and then the plugin bundle is installed there. This works fine for the default, but I don't know how to override this for a custom install directory. Will this work?

**Comment by ycollet** [comment]
I think it will works. If I sets it to lib64/lv2, it will be installed into /usr/lib64/lv2/plugin.lv2
It'll be fine.

**Comment by ssj71** [comment]
I've just pushed this change to the master branch in git. Please let me know how to define the custom install directory and I'll add it to the readme.

**Comment by ycollet** [comment]
I just pushed a pull request with a fix for the installation.

**Comment by ssj71** [comment]
merged. thanks.
