### ISSUE TITLE
ewham segfault

### ISSUE THREAD

**Issue by OrsonMaxwell** [ssj71/infamousPlugins#20]
Hello!

I'm using the latest KXStudio distro and I'm trying to run ewham in Carla on a Dell Latitude E6410 laptop (intel i5).
Basically it runs ok, but it seem to crash carla with the segmentation error every time I try to push a loud signal through.
I'm reproducing this issue reliably when plugging my guitar on or off while the other end of the cable is plugged in (which makes a loud pop obviously)

Please tell me what additional information do you require?
Thanks.

**Comment by ssj71** [comment]
Thanks for the bug report. I'll get to this as soon as I get a chance but things have been pretty busy lately. I assume you just had whatever kxstudio installed or did you build it yourself?
Thanks!

**Comment by OrsonMaxwell** [comment]
I discussed this with falkTX and he believes this can be a bug in the plugin host I'm using, so he had me open an issue in the carla repo as well.
I'll test this issue in a different plugin host and get back to you both with the result. I'll also try to keep you updated if we find anything else out.
I`m using the KXStudio version that is currently posted on the website - I just installed it out of the box and tweaked some realtime priorities afterwards.

P.S. Thank you for your work! Your plugin actually beats my hardware digitech unit, so I'm happy to use it.

**Comment by ssj71** [comment]
I tried a minimal test with another host (jalv) and couldn't reproduce the issue so I'm guessing its carla. Let me know if you have further issues.

Thats great to hear that you like it more than your hardware! Are you using it for guitar or voice or something else? I actually made ewham because I wanted to have a digitech whammy. :)

**Comment by OrsonMaxwell** [comment]
Yeah, it seems so indeed. Sorry for misopening this issue - at the time it seemed logical.

I have a Digitech Harmony Man unit which I mostly use for octaves for my guitar. Now that I have the luxury and freedom of DSP, I'll probably experiment with vocal pitching as well. And yeah, I also wanted a pedal controlled whammy for things like Joe Satriani does :) Thanks again!

**Comment by OrsonMaxwell** [comment]
After investigating this issue with falkTX, it seems that carla is not to blame here. I was able to crash the plugin both in carla and jalv. Also I was able to capture the input to a WAV file that crashes the plugin reliably (at least on my system).
Unfortunately I seem to be unable to build ntk in order to build ewham in debug mode.
Can we investigate this issue further?

**Comment by ssj71** [comment]
sure, you shouldn't need ntk, especially for ewham since I never made an NTK gui for it. Do you have a recent copy of the master branch? In the last few weeks even I've made some changes to the cmake files to handle this better. I still have more to do before making a full release, but master shouldn't have any problems.

**Comment by OrsonMaxwell** [comment]
Yes, I grabbed the code yesterday.
I successfully built the no-GUI target, but I'll probably need to install it manually. I'll get back here when I have any results.

**Comment by OrsonMaxwell** [comment]
Ok I built ewham from sources and installed it manually. I'm glad to announce that I failed to reproduce this error using two different hosts and both the recorded stimulus and real-life cable popping.
I guess you already fixed this issue. Thanks a bunch - this makes my life so much better!

**Comment by ssj71** [comment]
well thats great news! Glad its working. Be sure to keep me in the loop if you have any more issues.

**Comment by ranolfi** [comment]
Hi. I have been able to reproduce this issue consistently by loading my cpu cores with a high priority process, like so:

`sudo chrt 55 stress -c 4`

Do that and invoke `<Ctrl>+C` a few times, and you'll find that the _jackdbus_ process becomes unresponsive in short order - and, as a result, Carla (or whatever other plugin host you're using) will crash. Cadence becomes unresposive, as does pulseaudio, and both must be SIGKILL'd, as does _jackdbus_ (that is, if it doesn't enter the 'uninterruptible' state, because if that happens, good luck! I usually have to [\[R\]EISUB](https://en.wikipedia.org/wiki/Magic_SysRq_key#Uses) my machine at that point).

So, this issue is still valid from where I stand (unfortunately). Can we get it re-opened?
