### ISSUE TITLE
location of (f)ltk package

### ISSUE THREAD

**Issue by peter-zenk** [ssj71/infamousPlugins#53]
In the Readme the - already updated - location for the (f)ntk package seems to be out-of-date again.

Could not find a libntk.so anywhere around, nor a way of building it

**Comment by ssj71** [comment]
Hey I appreciate the heads up. Unfortunately the vanilla fltk doesn't actually work with plugins because it doesn't provide the x window handle (unless it has changed and I'm unaware), which was one of the primary purposes of the NTK fork. And the NTK author has removed all his projects from anywhere online, so I'll have to hunt down if someone else is hosting a copy somewhere. Sorry for the inconvenience.

**Comment by peter-zenk** [comment]
You are probably in a better position to judge: 
is the following package usable by any chance? (Maybe I'll try myself within the next couple of days)

https://archlinux.org/packages/community/x86_64/ntk/

**Comment by trebmuh** [comment]
@ssj71 : https://github.com/falkTX/ntk & https://github.com/Stazed/ntk

**Comment by peter-zenk** [comment]
Thanks for the info. Tried to compile with that package specified and - after messing around with missing libraries for a while - a now got the lushlife GUI up and running again.

Big thank you for this wonderful plugin. Gives my limited voice another dimension.

**Comment by ssj71** [comment]
Thanks guys.
